config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :flights do 
  	member do 
  	get :buy
    post :bought
    get :congratulation
    get :approve
   end

  end

  resources :seat_features do
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get 'home/index'



end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord

  has_many :seats
  has_many :tickets
  has_many :users, through: :tickets

  scope :sorted, lambda {order(:departure)}

  def sorted_by_location(f,t)
    Flight.where(:from => f).where(:to => t).where(approve: true).order(:departure)
  end

  def search(from,to)
    if from and to
        sorted_by_location(from,to)
      else
        Flight.where(approve: true)
      end
  end

end

app/models/location.rb
class Location < ApplicationRecord

end

app/models/seat.rb
class Seat < ApplicationRecord
  has_many :seat_features
   self.inheritance_column = nil
end

app/models/seat_feature.rb
class SeatFeature < ApplicationRecord
  belongs_to :seat

  scope :sorted, lambda { order(:seat_id => 'ASC')}
  scope :list, lambda {|query| where(["seat_id = ?","#{query}"])}

end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :user
	belongs_to :flight
	has_one :seat
end

app/models/user.rb
class User < ApplicationRecord

	has_many :tickets
	has_many :flights, through: :tickets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'home'
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  layout 'home'

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def index
    f = Flight.new
    @ticket = Ticket.new
    @flights = f.search(params[:from],params[:to])
    @un_approved = Flight.where(approve:false)
  end

  def show
    @flight = Flight.find(1)
  end

  def new
    @flight = Flight.new
  end

  def approve
  @flight = Flight.find(params[:id])
  @flight.update(approve: true)
  redirect_to flights_path
  end 
  def create
    @flight = Flight.new(flight_params)
    if @flight.save
      redirect_to(flight_path(@flight))
    else
      render('new')
    end
  end

  def edit
    @flight = Flight.find(params[:id])
  end

  def update
    @flight = Flight.find(params[:id])
    if @flight.update_attributes(flight_params)
      redirect_to(flight_path(@flight))
    else
      render('edit')
  end
end

  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy
  end

  def buy
    @flight = Flight.find(params[:id])  
    @user = current_user
  end

  def bought
    @flight = Flight.find(params[:id])
    @number_of_tickets = params[:tickets][:number_of_tickets]
    @seat_type = params[:tickets][:seat_type]
    @seat_type = params[:tickets][:seat_type]
    @user = current_user.id
    puts @seat_type.class
    Ticket.create(user_id: @user,flight_id: @flight.id,number_of_tickets: @number_of_tickets,seat_type: @seat_type)
     
     if @seat_type == "1"
        puts "hello 1"
        @update_seat_count = @flight.avaible_seats_first_class.to_i - @number_of_tickets.to_i;
        puts @update_seat_count
        @flight.update(avaible_seats_first_class: @update_seat_count)
     elsif @seat_type == "2"
      puts "hello 2"
        @update_seat_count = @flight.avaible_seats_bussiness_class.to_i - @number_of_tickets.to_i;
        @flight.update(avaible_seats_bussiness_class: @update_seat_count)
        puts @update_seat_count
     elsif @seat_type == "3"
      puts "hello 3"
        @update_seat_count = @flight.avaible_seats_sconomy_class - @number_of_tickets;
        @flight.update(avaible_seats_sconomy_class: @update_seat_count)
        puts @update_seat_count
     end

      redirect_to(congratulation_flight_path)
  end

  def congratulation
  end

  def flight_params
    params.require(:flight).permit(:from,:to,:departure,:first_class_seats,:bussiness_class_seats,
    :economy_class_seats,:avaible_seats_first_class,:avaible_seats_bussiness_class,:avaible_seats_sconomy_class,
    :price_first_class,:price_bussiness_class,:price_economy_class,:approve)
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

layout 'home'

def index
   @flights = Flight.sorted
end

end

app/controllers/seat_features_controller.rb
class SeatFeaturesController < ApplicationController

   layout 'home'
  def index
    @features1 = SeatFeature.list(1)
    @features2 = SeatFeature.list(2)
    @features3 = SeatFeature.list(3)
  end

  def new
    @feature = SeatFeature.new()
  end

  def create
      @feature = SeatFeature.new(seat_feature_params)
      if @feature.save
        redirect_to(seat_features_path)
      else
        render('new')
      end
  end

  def edit
    @feature = SeatFeature.find(params[:id])
  end

  def update
    @feature = SeatFeature.find(params[:id])
    if @feature.update_attributes(seat_feature_params)
      redirect_to(seat_features_path)
    else
      render('edit')
    end
  end

  def delete
    @feature = SeatFeature.find(params[:id])
  end

  def destroy
    @feature = SeatFeature.find(params[:id])
    @feature.destroy
    redirect_to(seat_feature_path)
  end

 def seat_feature_params
   params.require(:seat_feature).permit(:seat_id,:feature)
 end

end

app/controllers/ticket_controller.rb
class TicketController < ApplicationController
def ticket_params
    params.require(:ticket).permit(:user_id,:flight_id,:number_of_tickets,:seat_type)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/seat_features_helper.rb
module SeatFeaturesHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/flights/_form.html.erb
<table summary="Adding New Flight" class="table" style="background:rgb(240,240,240)">
  <tr>
    <th>From</th>
    <td><%= f.select(:from, Location.all.map {|s| [s.city]} ) %></td>
  </tr>
  <tr>
    <th>To</th>
    <td><%= f.select(:to, Location.all.map {|s| [s.city]} ) %></td>
  </tr>
  <tr>
    <th>Date and Time</th>
    <td><%= f.datetime_select(:departure, :minute_step => 15 ) %></td>
  </tr>
  <tr>
    <th>number of First class seats</th>
    <td><%= f.number_field(:first_class_seats, :max => 200 ) %></td>
  </tr>
  <tr>
    <th>number of bussiness class seats</th>
    <td><%= f.number_field(:bussiness_class_seats, :max => 200 ) %></td>
  </tr>
  <tr>
    <th>number of Economy class seats</th>
    <td><%= f.number_field(:economy_class_seats, :max => 200 ) %></td>
  </tr>

  <tr>
    <th>price of First class seat</th>
    <td><%= f.number_field(:price_first_class) %></td>
  </tr>
  <tr>
    <th>price of bussiness class seat</th>
    <td><%= f.number_field(:price_bussiness_class) %></td>
  </tr>
  <tr>
    <th>price of economy class seat</th>
    <td><%= f.number_field(:price_economy_class) %></td>
  </tr>
  <tr>
    <th>approve</th>
    <td><%= f.check_box(:approve) %></td>
  </tr>
</table>

app/views/flights/approve.html.erb
<p> Hi sheikh </p>

app/views/flights/buy.html.erb
<div class="container" style="width: 35% ;margin-top:5%; height:100%">
  <h2 class="text-center" style="margin-top: 5%" > <b> Buy Tickets </b> </h2>

  <%= form_for :tickets, url: 'bought' do |f| %>
  	<table summary="Buy Ticket" class="table text-center container" style="background:rgb(240,240,240)">
  <tr>
    <th>From</th>
    <td><%= @flight.from  %> </td>
  </tr>
  <tr>
    <th>To</th>
    <td><%= @flight.to %></td>
  </tr>
  <tr>
    <th>Departure</th>
    <td><%= @flight.departure %></td>
  </tr>
  <tr>
    <th>Seat</th>
    <td><%= f.collection_select :seat_type, Seat.order(:type),:id,:type %></td>
    <td><%= f.number_field(:number_of_tickets,max: 10, min: 1) %>
  </tr>
</table>
    <div class="text-center" style="allignemnt:center; margin-top:10px">
      <%= button_to 'Buy',bought_flight_path(f), :class => 'btn btn-primary btn-lg' %>
    </div>

  <% end %>
</div>

app/views/flights/congratulation.html.erb
<dir class="container text-center" style="margin-top: 5%">
	<h5>
		You tickets have been booked 
	</h5>
</dir>

app/views/flights/edit.html.erb
<div class="container" style="width: 35% ;margin-top:5%; height:100%">
  <h2>Edit Flight</h2>

  <%= form_for(@flight) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div style="allignemnt:center; margin:10px">
      <%= f.submit("Update Flight", :class => 'btn btn-primary') %>
    </div>

  <% end %>
</div>

app/views/flights/index.html.erb
<div>
<% if !current_user.manager  %>
     <h2 class="text-center" style="margin-top: 5%" > <b> Search Flights </b> </h2>
  <div class="container table" style="text-align: center;background-color: rgb(240,240,240); margin-top:3%;margin;5px" >
      <div class = 'col-sm-3'>
        <h2>Search</h2>
        <%= form_tag flights_path,:method => :get do %>
        <table  class="table">
          <thread>
            <tr>
              <td>
                <h5>From:</h5>
              </td>
              <td>
                <%= text_field_tag :from, params[:from]%>
              </td>
            </tr>
          </thread>
          <thread>
              <tr>
                <td>
                  <h5>To:</h5>
                </td>
              <td>
                <%= text_field_tag :to, params[:to]%>
              </td>
              </tr>
          </thread>
          <thread>
              <tr>
                <td>
              <%=submit_tag("Search",:name => nil) %>
                </td>
              </tr>
          </thread>
        </table>
        <% end %>
    </div>
    <div class = 'col-sm-9'>
    <h2>Schedule</h2>
        <table class="table">
          <tr class="header">
            <th>From</th>
            <th>To</th>
            <th>Departure</th>
            <th>Price First Class</th>
            <th>Price Bussiness Class</th>
            <th>Price Economy Class</th>
            <th>Buy</th>
          </tr>
          <% @flights.each do |f| %>
          <tr>
            <td><%= f.from %></td>
            <td><%= f.to %></td>
            <td><%= f.departure %></td>
            <td><%= f.price_first_class %></td>
            <td><%= f.price_bussiness_class %></td>
            <td><%= f.price_economy_class %></td>
            <td><%= button_to "Buy", buy_flight_path(f),method: :get, class: "btn btn-primary" %></td>
          </tr>
          <% end %>
        </table>
    </div>
  </div>
  <% else %>
   <h2 class="text-center" style="margin-top: 5%" > <b> Flight Details </b> </h2>
  <div  class="container" style="text-align: center;background-color: rgb(240,240,240); margin-top:3%;margin;5px">
   <table class="table">
          <tr class="header">
            <th>From</th>
            <th>To</th>
            <th>Departure</th>
            <th>Price First Class</th>
            <th>Price Bussiness Class</th>
            <th>Price Economy Class</th>
            <th>Buy</th>
          </tr>
          <% if @un_approved.present? %>
            <% @un_approved.each do |f| %>
            <tr>
              <td><%= f.from %></td>
              <td><%= f.to %></td>
              <td><%= f.departure %></td>
              <td><%= f.price_first_class %></td>
              <td><%= f.price_bussiness_class %></td>
              <td><%= f.price_economy_class %></td>
              <td><%= button_to "Approve", approve_flight_path(f),method: :get, class: "btn btn-primary" %></td>
            </tr>
            <% end %>
          <% end %>
        </table>
        </div>
<% end %>
</div>

app/views/flights/new.html.erb
<div class="container" style="width: 35% ;margin-top:5%; height:100%">
  <h2>Add Flight Details</h2>

  <%= form_for(@flight) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div style="allignemnt:center; margin:10px">
      <%=f.submit("Add Flight",:class => 'btn btn-primary') %>
    </div>

  <% end %>
</div>

app/views/flights/show.html.erb
<div class="container" style="width: 50% ;margin-top:5%; height:100%">
  <h2>Flight Detail</h2>
  <table summary="Flight detail view" class="table" style="background:rgb(240,240,240)">
    <tr>
      <th>From</th>
      <td><%= @flight.from %></td>
    </tr>
    <tr>
      <th>To</th>
      <td><%= @flight.to %></td>
    </tr>
    <tr>
      <th>Departure </th>
      <td><%= @flight.departure %></td
    </tr>
    <tr>
      <th> Total First Class</th>
      <td><%= @flight.first_class_seats %></td>
    </tr>
    <tr>
      <th> Total Bussiness Class</th>
      <td><%= @flight.bussiness_class_seats %></td>
    </tr>
    <tr>
      <th> Total Economy Class</th>
      <td><%= @flight.economy_class_seats %></td>
    </tr>
    <tr>
      <th> Available First Class</th>
      <td><%= @flight.avaible_seats_first_class %></td>
    </tr>
    <tr>
      <th> Available Bussiness Class</th>
      <td><%= @flight.avaible_seats_bussiness_class %></td>
    </tr>
    <tr>
      <th> Available Economy Class</th>
      <td><%= @flight.avaible_seats_sconomy_class %></td>
    </tr>
    <tr>
      <th>Price First Class Seat </th>
      <td><%= @flight.price_first_class %></td>
    </tr>
    <tr>
      <th>Price Bussiness Class Seat </th>
      <td><%= @flight.price_bussiness_class %></td>
    </tr>
    <tr>
      <th>Price Economy Class Seat </th>
      <td><%= @flight.price_economy_class %></td>
    </tr>
    <tr>
      <th>approved</th>
      <td><%= @flight.approve ? 'Yes' : 'No' %></td>
    </tr>
  </table>
  <%= button_to "Back", flights_path, :method => :get, :class => 'btn btn-primary' %>

</div>

app/views/home/index.html.erb
<div class="container">
<div class="row" style="margin-top: 5%">
  <div class="col-sm-12">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="padding: 0.1%; background-color: transparent;" >
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="lahore.jpg" alt="home" style="width: 100%; max-height:700px;">
          <div class="carousel-caption">
            <h3>Come Fly With</h3>
            <p>Enjoy every moment of your journey</p>
          </div>
        </div>

        <div class="item">
          <img src="islamabad.jpg" alt="home" style="width: 100%; max-height:700px">
          <div class="carousel-caption">
            <h3>Come Fly With</h3>
            <p>Enjoy every moment of your journey</p>
          </div>
        </div>

        <div class="item">
          <img src="karachi.jpg" alt="home" style="width: 100%; max-height:700px">
          <div class="carousel-caption">
            <h3>Come Fly With</h3>
            <p>Enjoy every moment of your journey</p>
          </div>
        </div>
      </div>
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
<div class="row" style="margin-top:10px;">
  <div class="col-sm-12" style="padding: 20px;margin-right: 0px">
    <h2 style="text-align: center;background-color: rgb(120,120,120); color: rgb(255,255,255);margin: 0 px;">Schedule</h2>
    <table  class="table text-center" style="background-color: rgb(240,240,240);padding: 20px">
      <thead>
       <tr>
        <th class="tablestyle" style="font-weight: bold;">From</th>
        <th class="tablestyle" style="font-weight: bold;">To</th>
        <th class="tablestyle" style="font-weight: bold;">Departure</th>
        <th class="tablestyle" style="font-weight: bold;">Price First Class</th>
        <th class="tablestyle" style="font-weight: bold;">Price Bussiness Class</th>
        <th class="tablestyle" style="font-weight: bold;">Price Economy Class</th>
      </tr>
    </thead>
    <% @flights.each do |f| %>
      <thread>
        <tr>
        <th class="tablestyle"><%= f.from %> </th>
        <th class="tablestyle"><%= f.to %> </th>
        <th class="tablestyle"><%= f.departure %> </th>
        <th class="tablestyle"><%= f.price_first_class %> </th>
        <th class="tablestyle"><%= f.price_bussiness_class %> </th>
        <th class="tablestyle"><%= f.price_economy_class %> </th>

        <th>
        </tr>

    <% end %>
</table>
</div>
</div>
</div>

app/views/layouts/_footer.html.erb
<div style="height:20px"></div>
<footer style="height: 70px; margin:0; clear:both; width: 100%;  position: relative; background-color: rgb(240,240,240);">
  <div class="container">
   <h4>Airfly Airline</h4>
   <h5>Copyrights</h5>
   </div>
 </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom: 0px; background-color: rgb(240,240,240); ">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="navbar-brand">Airfly</li>
        <li class="active"> <%= link_to "Home", 'home/index' %> </li>
        <li> <%= link_to "Flights Schedule", flights_path %> </li>
        <li><a href="#">Tickets</a></li>
        <li><a href="#">Book Flight</a></li>
      </ul>
      <table style="margin-top:1%">
        <tr>
     <td style="background-color:rgb(140,140,140)">
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, :method => :delete, class: "btn btn-primary" %>
      <% else %>
          <%= button_to "Sign in", user_session_path, class: "btn btn-primary"  %>
      <% end %>
    </td>
    <tr>
  </table>
   </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airfly</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="generator" content=
  "HTML Tidy for HTML5 for Windows version 5.2.0">
  <meta charset="utf-8">
  <meta name="viewpoint" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</script>
<title> FlyAir Online Booking </title>
</head>
<body style="margin-left: 10%; margin-right: 10%;background-color: rgb(200,200,200);">
  <nav class="navbar navbar-default navbar-fixed-top" style="margin-bottom: 0px; background-color: rgb(240,240,240); ">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="navbar-brand">Airfly</li>
        <li class="active"> <%= link_to "Home", '/' %> </li>
        <li> <%= link_to "Flights Schedule", flights_path %> </li>
        <li> <%= link_to "Seat Feature", seat_features_path %></li>
      </ul> 
      <table style="margin-top:1%">
        <tr>
     <td style="background-color:rgb(140,140,140)">
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, :method => :delete, class: "btn btn-primary" %>
      <% else %>
          <%= button_to "Sign in", user_session_path, class: "btn btn-primary"  %>
      <% end %>
    </td>
    <tr>
  </table>
   </div>
 </nav>
 
   <%= yield %>

<div class="push">
<footer class="footer" style="background: rgb(240,240,240); margin-top: 2%" >
  <div class="container">
   <h4>Airfly Airline</h4>
   <h5>Copyrights</h5>
   </div>
 </div>
</footer>
</div>
</body>

</html>

app/views/seat_features/_form.html.erb
<table summary="feature form fields" class="form-signin">
  <tr>
    <th>Seat</th>
    <td><%= f.select(:seat_id, Seat.all.map {|s| [s.type,s.id]} ) %></td>
  </tr>
  <tr>
    <th>feature</th>
    <td><%= f.text_field(:feature, :size => 40 ,:max_length => 40) %></td>
  </tr>
</table>

app/views/seat_features/edit.html.erb
<div style="padding:10%"/>
<%= link_to("<< Back to List", seat_features_path, :class => 'back-link') %>
</div>
<div class="container" style="width: 35% ;margin-top:10%; height:100%">
  <h2>add Seat feature</h2>

  <%= form_for(@feature) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update feature") %>
    </div>

  <% end %>
</div>

app/views/seat_features/index.html.erb
<div class="container">
  <h2>Seat feature</h2>
<div class="row table" style="text-align: center;background-color: rgb(240,240,240); margin-top:50px;margin;5px" >
 <div class="col-sm-4" style="text-align: center;background-color: rgb(240,240,240); margin-top:50px;margin;5px" >
      <h2> First Class </h2>
      <table class="table"  summary="f list">
        <% @features1.each do |f| %>
        <tr>
           <td><h5 style="margin:10px"> <%= f.feature %> </h5> </td>
        </tr>
        <% end %>
      </table>
  </div>
 <div class="col-sm-4" style="text-align: center;background-color: rgb(240,240,240); margin-top:50px;margin;5px" >
     <h2> Bussiness Class </h2>
     <table class="table" summary="f list">
       <% @features2.each do |f| %>
       <tr>
         <td><h5 style="margin:10px"> <%= f.feature %> </h5> </td>
       </tr>
       <% end %>
     </table>
 </div>
 <div class="col-sm-4" style="text-align: center;background-color: rgb(240,240,240); margin-top:50px;margin;5px" >
     <h2> Economy Class </h2>
     <table class="table" summary="f list">
       <% @features3.each do |f| %>
       <tr>
       <td> <h5 style="margin:10px"> <%= f.feature %> </h5> </td>
       </tr>
       <% end %>
     </table>
 </div>

</div>

</div>

app/views/seat_features/new.html.erb
<%= link_to("<< Back to List", seat_features_path, :class => 'back-link') %>

<div class="container" style="width: 35% ;margin-top:10%; height:100%">
  <h2>New Flight</h2>

  <%= form_for(@feature) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div style="allignemnt:center; margin:10px">
      <%= f.submit("Add feature") %>
    </div>

  <% end %>
</div>